version: "3.8"


services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./loki:/etc/loki
      - ./loki/data:/wal
    command: -config.file=/etc/loki/local-config.yaml

  # promtail:
  #   image: grafana/promtail:2.2.1
  #   container_name: promtail
  #   restart: unless-stopped
  #   volumes:
  #     - ./promtail:/etc/promtail
  #   command: -config.file=/etc/promtail/config.yml
  
  # uptime-kuma:
  #   image: louislam/uptime-kuma:1
  #   container_name: uptime-kuma
  #   restart: unless-stopped
  #   ports:
  #     - "3001:3001"
  #   volumes:

  #     - ./uptime-kuma:/app/data